### ISSUE TITLE
pomysły na wyścigi pociągów

### ISSUE THREAD

**Issue by SoGreeno** [lisqu16/wyscigipociagow#1]
**<h1>nowe pociągi</h1>**
złoty pociąg - masz 10%-15% szans aby nim zostać, kosmetyczne. nie robi że bardziej wygrywasz
![zuotypocionk](https://user-images.githubusercontent.com/59972034/131220867-c66dda9a-f6a3-467a-ab7a-8f6fbd653c33.png)

**<h1>mały detal</h1>**
na końcu torów jest stacja, jak na niej jesteś to wygrywasz wyścig, zamiast zatrzymywać się na końcu torów

**Comment by guamencja** [comment]
zamykam z wiadomych powodów XD
